# Generated by Django 3.1 on 2025-05-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='', max_length=100),
        ),
    ]
